### ISSUE TITLE
Error running eko convolute

### ISSUE THREAD

**Issue by scarlehoff** [NNPDF/pineko#66]
When playing around with some of the `pineko` options I find the following error:

```
~$ pineko convolute data/grids/200/E906deut_bin_09.pineappl.lz4 data/ekos/200/E906deut_bin_09.tar test 3 3                                                                         
┌───────────────┐
│ Computing ... │
└───────────────┘
   data/grids/200/E906deut_bin_09.pineappl.lz4
 + data/ekos/200/E906deut_bin_09.tar
 = test
 with max_as=3, max_al=3, xir=1.0, xif=1.0
Traceback (most recent call last):
  File "/home/juacrumar/.cache/pypoetry/virtualenvs/pinefarm-HwI1B8mU-py3.10/bin/pineko", line 8, in <module>
    sys.exit(command())
  File "/home/juacrumar/.cache/pypoetry/virtualenvs/pinefarm-HwI1B8mU-py3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/juacrumar/.cache/pypoetry/virtualenvs/pinefarm-HwI1B8mU-py3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/juacrumar/.cache/pypoetry/virtualenvs/pinefarm-HwI1B8mU-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/juacrumar/.cache/pypoetry/virtualenvs/pinefarm-HwI1B8mU-py3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/juacrumar/.cache/pypoetry/virtualenvs/pinefarm-HwI1B8mU-py3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/juacrumar/.cache/pypoetry/virtualenvs/pinefarm-HwI1B8mU-py3.10/lib/python3.10/site-packages/pineko/cli/convolute.py", line 52, in subcommand
    _grid, _fk, comp = evolve.evolve_grid(
  File "/home/juacrumar/.cache/pypoetry/virtualenvs/pinefarm-HwI1B8mU-py3.10/lib/python3.10/site-packages/pineko/evolve.py", line 133, in evolve_grid
    alphas_values = [op["alphas"] for op in operators["Q2grid"].values()]
  File "/home/juacrumar/.cache/pypoetry/virtualenvs/pinefarm-HwI1B8mU-py3.10/lib/python3.10/site-packages/pineko/evolve.py", line 133, in <listcomp>
    alphas_values = [op["alphas"] for op in operators["Q2grid"].values()]
KeyError: 'alphas'
```

Am I doing something wrong (`pineko theory fks` work for the same set of grids and theory)? Or is there a bug somehwere?

**Comment by scarlehoff** [comment]
I'm using pineline installed from pip in a clean environment so it should be consistent.

Sadly I cannot check because montblanc just went down..., so I'll let you know next wek.

**Comment by AleCandido** [comment]
Did you compute the EKO yourself or were you using an existing one?

**Comment by AleCandido** [comment]
However, I see that your "clean environment" is actually `pinefarm` Poetry environment:
```
/home/juacrumar/.cache/pypoetry/virtualenvs/pinefarm-HwI1B8mU-py3.10/...
```
Are you sure you really used `pip` and not Poetry? And are you sure you didn't use Poetry before?

**Comment by scarlehoff** [comment]
I cannot check now (which means there could be some garbage I don't remember now!) but I think everything, poetry included, was installed from 0 last week.

**Comment by scarlehoff** [comment]
I'll retry next week. 

I did compute the eko myself though, so it was the same pineko computing the eko and trying to convolute

**Comment by AleCandido** [comment]
I'm not blaming you: I know the error, I'm just making hypothesis.
It's our fault in the first place, unfortunately this very long migration was very likely to introduce this kind of bugs: it was a delicate operation, and left us in this intermediate/incomplete state for a too long time. I'll try to finalize as much as possible in the next few weeks.
